### ISSUE TITLE
Integer nums, but can read in floats, precision loss?

### ISSUE THREAD

**Issue by mborowczak** [UW-COSC-2030-FA-2017/lab1-processlist-jspauld5#1]
Looks like you're storing integers -

`int num1, num2, num3, num4;`

but processing doubles -

`double buffer = 0, bufferPrev = buffer;`

...then...

`num1 = buffer;`
`num2 = ...`
`num3 = ...`
`num4 = ...`

Pretty sure this has an easy fix!

**Comment by jspauld5** [comment]
Thank you, this issue will be fixed. @mborowczak
